# Generated by Django 5.2.17 on 2026-09-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('categoria', models.CharField(default='General', max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('alerta_minimo', models.PositiveIntegerField(default=5)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
