# Generated by Django 5.2.17 on 2026-09-22 13:35

import django.utils.timezone
from django.db import migrations, models


def asignar_codigos_unicos(apps, schema_editor):
    Producto = apps.get_model('inventario', 'Producto')
    contador = 1
    for p in Producto.objects.all().order_by('id'):
        p.codigo = f"PROD-{contador:03d}"
        p.save(update_fields=['codigo'])
        contador += 1


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField(verbose_name='Pregunta del usuario')),
                ('respuesta', models.TextField(verbose_name='Respuesta de Ollama')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
            ],
            options={
                'db_table': 'consultas_ia',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['categoria', 'nombre']},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='actualizado_el',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='alerta_minimo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_existente',
            field=models.IntegerField(default=0, verbose_name='Cantidad disponible'),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default='PROD000', max_length=50, verbose_name='Código único'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=5, verbose_name='Stock mínimo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(max_length=100, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterModelTable(
            name='producto',
            table='productos',
        ),
        migrations.RunPython(asignar_codigos_unicos),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código único'),
        ),
    ]
