# Generated by Django 5.2.17 on 2026-09-23 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_consultaia_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_existente',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'La cantidad no puede ser negativa.')], verbose_name='Cantidad disponible'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, 'El precio no puede ser negativo.')], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0, 'El stock mínimo no puede ser negativo.')], verbose_name='Stock mínimo'),
        ),
    ]
