# Generated by Django 5.2.17 on 2026-09-27 17:18

from django.db import migrations, models


def poblar_categorias(apps, schema_editor):
    """Crea el catalogo a partir de las categorias ya usadas por los productos."""
    Producto = apps.get_model("inventario", "Producto")
    Categoria = apps.get_model("inventario", "Categoria")
    nombres = (Producto.objects.exclude(categoria="")
               .values_list("categoria", flat=True).distinct())
    for nombre in nombres:
        Categoria.objects.get_or_create(nombre=nombre)


def borrar_categorias(apps, schema_editor):
    apps.get_model("inventario", "Categoria").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_cantidad_existente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Categoría')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.RunPython(poblar_categorias, borrar_categorias),
    ]
